### ISSUE TITLE
Using customComponent, other button's onPress does not work.

### ISSUE THREAD

**Issue by MahmonirB** [KirillGudkov/react-native-in-app-message#14]
when I use customComponent, I modify some button to do various actions, but just onPress of Notification is done.
I commented onPress, so click on sample buttons (in notification) caused crash due to undefined function.
how ca I handle it?

**Comment by kirgudkov** [comment]
@MahmonirB Hi, it's known issue - one of the root components is `TapGestureHandler`. Probably in your case it actually catch both events: `onPress` from `TouchableOpacity` and `onHandlerStateChanged` from `TapGestureHandler`
And I don't know how to fix this collision so far

All can I advice You - to use `TapGestureHandler` instead of `TouchableOpacity` or any other RN touchables

check [the example](https://github.com/KirillGudkov/in-app-message-example/blob/78479dbb7b9662974919b29a67817bea2d9f687f/App.js#L42-L78) I wrote, hope it helps You

What was cause of crash - probably you made some mistake, in [example](https://github.com/KirillGudkov/in-app-message-example) you'll can see how i do it :)  no crashes no errors
